#IISViewer Mod Configuration
#Wed Jul 08 19:29:41 OMST 2026
anchor-x=1.0
anchor-y=1.0
enabled=true
gradient-high-b=0
gradient-high-g=102
gradient-high-r=0
gradient-low-b=0
gradient-low-g=0
gradient-low-r=153
offset-x=8
offset-y=8
show-empty-slots=false
